"""REST API routes for GUIN web frontend."""

from __future__ import annotations

import asyncio
import platform
from dataclasses import asdict
from pathlib import Path
from typing import Any

from fastapi import APIRouter
from pydantic import BaseModel, Field

from guin.core.config import GuinCLIConfig, apply_config_env
from guin.provenance.diff import provenance_diff
from guin.provenance.tracker import ProvenanceTracker
from guin.api.websocket import HUB

router = APIRouter(prefix="/api/v1", tags=["guin"])


def ok(data: Any) -> dict[str, Any]:
    return {"status": "ok", "data": data}


def err(message: str) -> dict[str, Any]:
    return {"status": "error", "message": message}


def _render_generated_code(instruction: str, bids_dir: str, output_dir: str) -> str:
    return (
        "from pathlib import Path\n\n"
        "# Auto-generated by GUIN Web API planner\n"
        f"instruction = {instruction!r}\n"
        f"bids_dir = Path({bids_dir!r})\n"
        f"output_dir = Path({output_dir!r})\n\n"
        "print('Instruction:', instruction)\n"
        "print('BIDS dataset:', bids_dir)\n"
        "print('Output directory:', output_dir)\n"
        "# TODO: replace with full CodeAct planning + execution pipeline.\n"
    )


def _summary_stats(dataset_path: Path) -> dict[str, Any]:
    subs = set()
    ses = set()
    tasks = set()
    modalities = set()
    files = 0
    for p in dataset_path.rglob("*"):
        if not p.is_file():
            continue
        files += 1
        name = p.name
        parts = name.split("_")
        for token in parts:
            if token.startswith("sub-"):
                subs.add(token[4:])
            if token.startswith("ses-"):
                ses.add(token[4:])
            if token.startswith("task-"):
                tasks.add(token[5:])
        suf = p.suffix.lower()
        if "anat" in str(p.parent):
            modalities.add("anat")
        if "func" in str(p.parent):
            modalities.add("func")
        if "dwi" in str(p.parent) or "_dwi" in name:
            modalities.add("dwi")
        if suf == ".edf":
            modalities.add("eeg")
    return {
        "files": files,
        "subjects": len(subs),
        "sessions": len(ses),
        "tasks": sorted(tasks),
        "modalities": sorted(modalities),
    }


class RunRequest(BaseModel):
    instruction: str
    bids_dir: str
    output_dir: str
    model: str = "claude-sonnet-4-20250514"
    dry_run: bool = False


class ValidateRequest(BaseModel):
    dataset_path: str


class ToolRunRequest(BaseModel):
    payload: dict[str, Any] = Field(default_factory=dict)


class ProvenanceDiffRequest(BaseModel):
    record_a: str
    record_b: str


class ReplayRequest(BaseModel):
    provenance_file: str


class ConfigUpdateRequest(BaseModel):
    container_dir: str | None = None
    model: str | None = None
    api_key: str | None = None
    bids_validator_path: str | None = None
    apptainer_binary: str | None = None


async def _run_execute(run_id: str, req: RunRequest) -> None:
    out_dir = Path(req.output_dir).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    tracker = ProvenanceTracker(out_dir, llm_model_name=req.model)
    tracker.track_instruction(req.instruction)

    HUB.append_log(run_id, f"[planner] Starting run for model={req.model}")
    _emit = HUB.get_run(run_id)
    if _emit and _emit.logs:
        await HUB.publish(run_id, ok({"type": "log", "run_id": run_id, "line": _emit.logs[-1]}))

    code = _render_generated_code(req.instruction, req.bids_dir, req.output_dir)
    tracker.track_llm_code(code, iteration=1)

    script_path = out_dir / "guin_generated_plan.py"
    script_path.write_text(code, encoding="utf-8")
    HUB.append_log(run_id, f"[planner] Wrote generated plan: {script_path}")
    _emit = HUB.get_run(run_id)
    if _emit and _emit.logs:
        await HUB.publish(run_id, ok({"type": "log", "run_id": run_id, "line": _emit.logs[-1]}))

    await asyncio.sleep(0.1)
    prov_path = tracker.save()
    HUB.append_log(run_id, f"[provenance] Saved record: {prov_path}")
    _emit = HUB.get_run(run_id)
    if _emit and _emit.logs:
        await HUB.publish(run_id, ok({"type": "log", "run_id": run_id, "line": _emit.logs[-1]}))
    HUB.mark_done(run_id, success=True, provenance_file=str(prov_path))
    await HUB.publish(
        run_id,
        ok({"type": "state", "run_id": run_id, "state": HUB.list_runs(limit=100)}),
    )


@router.get("/status")
async def status() -> dict[str, Any]:
    from guin.mcp_server.server import CONFIG, list_containers

    cfg = GuinCLIConfig.load()
    apply_config_env(cfg)
    apptainer = str(CONFIG.APPTAINER_BINARY)
    container_runtime = "unknown"
    try:
        proc = await asyncio.create_subprocess_exec(
            apptainer,
            "--version",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        out, _err = await proc.communicate()
        if proc.returncode == 0:
            container_runtime = out.decode(errors="replace").strip() or apptainer
        else:
            container_runtime = f"{apptainer} (not available)"
    except FileNotFoundError:
        container_runtime = f"{apptainer} (not found)"

    containers = list_containers()
    return ok(
        {
            "python_version": platform.python_version(),
            "container_runtime": container_runtime,
            "available_containers": containers,
            "recent_runs": HUB.list_runs(limit=10),
        }
    )


@router.get("/tools")
async def tools() -> dict[str, Any]:
    from guin.mcp_server.server import mcp

    rows = await mcp.list_tools()
    payload = [
        {
            "name": str(getattr(t, "name", "")),
            "description": str(getattr(t, "description", "")).strip(),
            "input_schema": getattr(t, "inputSchema", {}),
            "output_schema": getattr(t, "outputSchema", {}),
        }
        for t in rows
    ]
    return ok({"tools": payload})


@router.post("/tools/{name}")
async def run_tool(name: str, req: ToolRunRequest) -> dict[str, Any]:
    from guin.mcp_server.server import mcp

    result = await mcp.call_tool(name, req.payload)
    if isinstance(result, tuple) and len(result) == 2:
        content, structured = result
        return ok({"content": content, "result": structured})
    return ok({"result": result})


@router.post("/run")
async def run_instruction(req: RunRequest) -> dict[str, Any]:
    from guin.mcp_server.server import validate_bids

    cfg = GuinCLIConfig.load()
    apply_config_env(cfg)
    chosen_model = cfg.model or req.model
    validation = validate_bids(str(Path(req.bids_dir).expanduser().resolve()))
    if not bool(validation.get("valid", False)):
        return err("BIDS validation failed")

    code = _render_generated_code(req.instruction, req.bids_dir, req.output_dir)
    run = HUB.new_run(
        instruction=req.instruction,
        bids_dir=req.bids_dir,
        output_dir=req.output_dir,
        model=chosen_model,
        dry_run=req.dry_run,
        generated_code=code,
    )
    if not req.dry_run:
        asyncio.create_task(
            _run_execute(
                run.run_id,
                RunRequest(
                    instruction=req.instruction,
                    bids_dir=req.bids_dir,
                    output_dir=req.output_dir,
                    model=chosen_model,
                    dry_run=req.dry_run,
                ),
            )
        )
    return ok({"run": HUB._run_to_dict(run), "validation": validation, "generated_code": code})


@router.post("/validate")
async def validate(req: ValidateRequest) -> dict[str, Any]:
    from guin.mcp_server.server import validate_bids

    dataset = Path(req.dataset_path).expanduser().resolve()
    result = validate_bids(str(dataset))
    stats = _summary_stats(dataset) if dataset.is_dir() else {}
    return ok({"validation": result, "summary": stats})


@router.get("/provenance")
async def provenance() -> dict[str, Any]:
    records: set[Path] = set()
    for run in HUB.list_runs(limit=100):
        p = run.get("provenance_file")
        if p:
            records.add(Path(str(p)))
    cwd_prov = Path.cwd() / "derivatives" / "guin" / "provenance"
    if cwd_prov.is_dir():
        records.update(cwd_prov.glob("session_*_provenance.jsonld"))
    rows = sorted(records, key=lambda p: p.name, reverse=True)
    return ok({"records": [str(p) for p in rows]})


@router.post("/provenance/diff")
async def provenance_diff_endpoint(req: ProvenanceDiffRequest) -> dict[str, Any]:
    pd = provenance_diff(Path(req.record_a), Path(req.record_b))
    return ok({"diff": asdict(pd), "markdown": pd.to_markdown()})


@router.post("/replay")
async def replay(req: ReplayRequest) -> dict[str, Any]:
    from guin.agent.workflow_gen import WorkflowGenerator

    from guin.cli.main import _load_workflow_json_from_provenance

    wf_json = _load_workflow_json_from_provenance(Path(req.provenance_file))
    if wf_json is None:
        return err("No serialized workflow JSON found in provenance.")
    gen = WorkflowGenerator.from_json(wf_json)
    gen.run(plugin="Linear")
    return ok({"replayed": True})


@router.get("/config")
async def get_config() -> dict[str, Any]:
    cfg = GuinCLIConfig.load()
    apply_config_env(cfg)
    container_rows: list[dict[str, Any]] = []
    if cfg.container_dir:
        cdir = Path(cfg.container_dir).expanduser()
        if cdir.is_dir():
            for sif in sorted(cdir.glob("*.sif")):
                stat = sif.stat()
                container_rows.append(
                    {
                        "name": sif.name,
                        "path": str(sif.resolve()),
                        "size_bytes": stat.st_size,
                    }
                )
    return ok({"config": cfg.to_dict(), "containers": container_rows})


@router.put("/config")
async def put_config(req: ConfigUpdateRequest) -> dict[str, Any]:
    current = GuinCLIConfig.load()
    merged = GuinCLIConfig(
        container_dir=req.container_dir if req.container_dir is not None else current.container_dir,
        model=req.model if req.model is not None else current.model,
        api_key=req.api_key if req.api_key is not None else current.api_key,
        bids_validator_path=(
            req.bids_validator_path
            if req.bids_validator_path is not None
            else current.bids_validator_path
        ),
        apptainer_binary=(
            req.apptainer_binary
            if req.apptainer_binary is not None
            else current.apptainer_binary
        ),
    )
    path = merged.save()
    apply_config_env(merged)
    container_rows: list[dict[str, Any]] = []
    if merged.container_dir:
        cdir = Path(merged.container_dir).expanduser()
        if cdir.is_dir():
            for sif in sorted(cdir.glob("*.sif")):
                stat = sif.stat()
                container_rows.append(
                    {
                        "name": sif.name,
                        "path": str(sif.resolve()),
                        "size_bytes": stat.st_size,
                    }
                )
    return ok({"config": merged.to_dict(), "path": str(path), "containers": container_rows})
